### ISSUE TITLE
大佬，v7权重跑出来ap都是0

### ISSUE THREAD

**Issue by LUO77123** [SSTato/YOLOv7_obb#1]
大佬，你是用的v7的权重跑的吗，我跑了一下几张图的数据集，ap都是0，用v5s的权重ap都有0.005,这是什么问题喃

**Comment by SSTato** [comment]
这个是在yolov5_obb的基础上改的，v7的收敛速度确实比v5要慢，你可以用我提供的权重当作预训练权重，可以快速收敛

**Comment by LUO77123** [comment]
我也很早用他的v5obb改了v7，效果很差我就放弃了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月18日(周二) 上午9:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SSTato/YOLOv7_obb] 大佬，v7权重跑出来ap都是0 (Issue #1)




 
这个是在yolov5_obb的基础上改的，v7的收敛速度确实比v5要慢，你可以用我提供的权重当作预训练权重，可以快速收敛
