### ISSUE TITLE
Hello, I want to train with your code, but the prompt is missing the file mentioned below, I don't know if you still update your code, I hope you see the message and reply to me, thank you very much

### ISSUE THREAD

**Issue by wei3044** [SSTato/YOLOv7_obb#10]
AssertionError: File not found: DOTA\dotas.yaml

**Comment by SSTato** [comment]
> AssertionError: File not found: DOTA\dotas.yaml

It is your dataset category information file and is set by yourself

**Comment by SSTato** [comment]
> > AssertionError: File not found: DOTA\dotas.yaml
> 
> It is your dataset category information file and is set by yourself

like this



# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path:
train: data/DOTA/train/images #images   # train images (relative to 'path')
val: data/DOTA/val/images #images  # val images (relative to 'path')
test: data/DOTA/val/images  #images # test images (optional)

# Classes
nc: 15  # number of classes
names: ['plane', 'baseball-diamond', 'bridge', 'ground-track-field', 'small-vehicle', 
        'large-vehicle', 'ship', 'tennis-court', 'basketball-court', 'storage-tank',  
        'soccer-ball-field', 'roundabout', 'harbor', 'swimming-pool', 'helicopter']  # class names

**Comment by SSTato** [comment]
> > AssertionError: File not found: DOTA\dotas.yaml
> 
> It is your dataset category information file and is set by yourself

like this
![image](https://user-images.githubusercontent.com/93987794/228010868-9de22b73-5ab3-47dd-9464-ff57e68903d9.png)
