### ISSUE TITLE
About the processing of HRSC datasets

### ISSUE THREAD

**Issue by wei3044** [SSTato/YOLOv7_obb#12]
Thank you very much for your answer, and I want to ask you how to handle the HRSC2016 dataset, I used the following code to convert, but an error was reported on colab, and finally I converted the txt file, I wonder if I can take a look at your processing code for this dataset, thank you very much, this question has bothered me for a long time.
![image](https://user-images.githubusercontent.com/59051955/228519836-5dff5602-1c92-4cc1-8c8a-c646442ba4e7.png)
![image](https://user-images.githubusercontent.com/59051955/228519927-f52ddeff-6c32-4146-8472-067eece9790b.png)
![image](https://user-images.githubusercontent.com/59051955/228520164-2f2dcabe-b405-4360-844b-98e073dd107a.png)
![image](https://user-images.githubusercontent.com/59051955/228520270-f76beb43-d973-4b65-b6c3-e54d22482efb.png)

**Comment by SSTato** [comment]
There are special conversion methods for HRSC2016 datasets online, but I can't remember where I saw them. You can search for them and process them in the following format，like DOTA datasets.

429.0 5.0 590.0 83.0 239.0 767.0 92.0 707.0 ship 0

**Comment by wei3044** [comment]
Thank you very much for your answer, but now I still can't run your code, I used the DOTA dataset for training, the following is my label format, but the training process will report an error, I also experimented with the YOLO format DOTA dataset, but still can't train, but, on other code, I can train these two datasets normally, so far, this problem has not been solved, sorry to disturb you again.I don't know why it doesn't work on your code, I'm sorry, I'm on a low level, I kindly ask you to help if you have time, thank you very much again
Dota dataset image：
![image](https://user-images.githubusercontent.com/59051955/231157188-5d5e32da-5787-450a-b725-b838996bf3fd.png)
DOTA dataset labels：
![image](https://user-images.githubusercontent.com/59051955/231157258-3abb42c4-120e-4132-808d-bbc2eb6d3263.png)
Dota dataset YOLO format labels
![image](https://user-images.githubusercontent.com/59051955/231157514-f4771376-3a89-496e-8498-cccce37825b5.png)
yaml file：
![image](https://user-images.githubusercontent.com/59051955/231157986-f9f9ecf6-0d4d-4128-8892-eddcda4c48b2.png)
Dataset catalog schema：
![image](https://user-images.githubusercontent.com/59051955/231158148-5ae24829-ce3f-43bb-837d-9287ea91af81.png)
The process of running the code：
![image](https://user-images.githubusercontent.com/59051955/231158684-92fdd85d-fbc7-4894-aefb-dd692338cb5b.png)
error:
![image](https://user-images.githubusercontent.com/59051955/231162976-7e521c4f-e8b7-4ce8-aef7-36e05c9386b1.png)

**Comment by wei3044** [comment]
Even if I use the DOTA dataset, the code will not run or this will happen, I'm sorry, I really don't know what the problem is, please how can you see it, can you help me see the problem, thank you very much!!
![image](https://user-images.githubusercontent.com/59051955/231165630-1822e684-2884-4c26-a8d4-5e2905000738.png)

![image](https://user-images.githubusercontent.com/59051955/231165402-c6cdd83f-f5b2-4aaa-bb26-864a90dc0dc4.png)
![image](https://user-images.githubusercontent.com/59051955/231165756-e490bcb4-63d3-4576-9c1d-8b020d8d4ee8.png)
![image](https://user-images.githubusercontent.com/59051955/231167334-780e20c5-9711-448a-b399-0427d48e7da3.png)

**Comment by SSTato** [comment]
> Even if I use the DOTA dataset, the code will not run or this will happen, I'm sorry, I really don't know what the problem is, please how can you see it, can you help me see the problem, thank you very much!! ![image](https://user-images.githubusercontent.com/59051955/231165630-1822e684-2884-4c26-a8d4-5e2905000738.png)
> 
> ![image](https://user-images.githubusercontent.com/59051955/231165402-c6cdd83f-f5b2-4aaa-bb26-864a90dc0dc4.png) ![image](https://user-images.githubusercontent.com/59051955/231165756-e490bcb4-63d3-4576-9c1d-8b020d8d4ee8.png) ![image](https://user-images.githubusercontent.com/59051955/231167334-780e20c5-9711-448a-b399-0427d48e7da3.png)

Obviously, this is a problem with dataset annotation, and here are detailed tutorials
https://zhuanlan.zhihu.com/p/358072483
