### ISSUE TITLE
Check out my repo

### ISSUE THREAD

**Issue by Suppersine** [SSTato/YOLOv7_obb#13]
I have forked & integrated your repo with other losses, such as KLD & KFIOU. No matter how many datasets I changed, our model didn't perform well. https://github.com/worldstar/yolov7-obb

the dataset I applied to our model is here: https://universe.roboflow.com/object-detection-bmosq/obb_front_back

**Comment by SSTato** [comment]
> 我已经将您的回购与其他损失（例如 KLD 和 KFIOU）分叉并整合。无论我更改了多少数据集，我们的模型都表现不佳。https://github.com/worldstar/yolov7-obb
> 
> 我应用于我们模型的数据集在这里：[https ://universe.roboflow.com/object-detection-bmosq/obb_front_back](https://universe.roboflow.com/object-detection-bmosq/obb_front_back)

In fact, I also experienced slow or difficult convergence during training. I don't know if this is one of the possible reasons for the poor results of your model. I used the trained model as a pre trained model to accelerate convergence.

**Comment by SSTato** [comment]
Compared to yolov5, yolov7 has slower and more difficult convergence. Of course, this is my personal feeling.
