### ISSUE TITLE
the model failed to read labels of a custom dataset

### ISSUE THREAD

**Issue by Suppersine** [SSTato/YOLOv7_obb#14]
I was running your model against my medical dataset, which is here: https://disk.yandex.com/d/NWIqw7W4VDtoZA

And according to this notebook: https://disk.yandex.com/d/aLgfDfIYIbYITA

, your program throws the "ignoring corrupt image/label: '[my custom tag]' is not in list" error
![image](https://github.com/SSTato/YOLOv7_obb/assets/49264553/a42246d6-c43a-477d-9324-30eaa1acec75)

which resulted in all arguments missing in the data reader
![image](https://github.com/SSTato/YOLOv7_obb/assets/49264553/c870dfda-983d-4372-9123-55620440afeb)

Could you please help me take a deep insight into this issue? so that we will know where the problem and the solution are.

**Comment by wei3044** [comment]
我也是这错误

**Comment by SSTato** [comment]
From an error perspective, it seems that there is a problem with the label category corresponding to the image. Is the category in the label file in the corresponding file?

**Comment by Suppersine** [comment]
Yes, they all match, in each train/val/test folder, there are two subfolders, /images (in .png or .jpg) and /labelTxt (in .txt)

**Comment by wei3044** [comment]
我的数据集在/hukaixuan19970627/yolov5_obb 这位博主的代码下运行没问题 可是运行您的代码 就是会出现上述的问题

**Comment by SSTato** [comment]
I have not encountered the same problem before, but it is obvious that there was a problem when loading the dataset. It may be due to the format of the image or the annotation file, which needs to be resolved using an exclusion method or by modifying the data loading in datasets.py. I have not encountered this problem and cannot reproduce it for resolution. Sorry.

**Comment by Suppersine** [comment]
Originally, my images were in .png, but now they're in .jpg. along with the tags in labelTxt subfolders, problem solved.
