### ISSUE TITLE
训练Dota的py文件可以上传吗?train_ota.py和普通train的差距很大嘛？

### ISSUE THREAD

**Issue by unbeliveyu** [SSTato/YOLOv7_obb#15]
大佬好，请问训练Dota的py文件可以上传吗?train_ota.py和普通train的差距很大嘛？如果不能公开，能告诉我您都改了哪些部分嘛？

**Comment by SSTato** [comment]
> 大佬好，请问训练Dota的py文件可以上传吗?train_ota.py和普通train的差距很大嘛？如果不能公开，能告诉我您都改了哪些部分嘛？

已经上传，更改部分参照yolov7

**Comment by unbeliveyu** [comment]
> > 大佬好，请问训练Dota的py文件可以上传吗?train_ota.py和普通train的差距很大嘛？如果不能公开，能告诉我您都改了哪些部分嘛？
> 
> 已经上传，更改部分参照yolov7
十分感谢您，祝顺利
