### ISSUE TITLE
关于Yolo格式转为Dota V1 server 提交

### ISSUE THREAD

**Issue by CS-Guo** [SSTato/YOLOv7_obb#19]
大佬您好,看到你将测试结果放到DOTAv1 Task1 Server上进行了验证？我最近也做这一步出现一些问题，但是我的转化结果可能有些问题，非常想请教一下您！非常感谢！

**Comment by SSTato** [comment]
可以详细描述你的问题

**Comment by CS-Guo** [comment]
就是我用yolo官方给的模型 ，在验证集上mAP差不多78，但是在DOTAv1 Task1 Server 上提交，收到结果邮件只有64，我感觉在转成DOTAv1 Task1 Server 提交格式的时候出现了问题，看到你的结果邮件的点很正常，想请教一下您！麻烦您了！

**Comment by SSTato** [comment]
如果你没有重新划分他的数据集，那只能是转换的时候有问题，需要自己排查一下
