### ISSUE TITLE
请问这个和hukaixuan的yolov5_obb有什么不同呢

### ISSUE THREAD

**Issue by HaoyuScut** [SSTato/YOLOv7_obb#3]
我阅读您的代码，但发现并不是yolov7，而是yolov5的网络使用了v7的模型，甚至连common文件都是v5的

**Comment by SSTato** [comment]
首先YOLOv7就是在YOLOv5 6.0的基础上改进的，论文里的许多方法在不同的YOLOv7模型中应用（如[YOLOv7-W6]等），光YOLOv7只用到了我提供的common.py，我不明白你所说的YOLOv7是什么意思，建议先了解YOLOv7和YOLOv5的区别。
