### ISSUE TITLE
Dimensionality issue when calculating OBB-NMS

### ISSUE THREAD

**Issue by Suppersine** [SSTato/YOLOv7_obb#4]
I was integrating MMRotate's KFIOU into your model, whose fork is here:
https://github.com/Suppersine/YOLOv7_obb_KFIOU

and here is my notebook:
https://colab.research.google.com/drive/1D4ez8AsZl4zuE-XDauLlWYxyyKd3NvjF?usp=sharing

With the training stage stuck due to the dime utils/general.py line 828:

```
Image sizes 640 train, 640 test
Using 0 dataloader workers
Logging results to runs/train/exp
Starting training for 10 epochs...

     Epoch   gpu_mem       box       obj       cls     theta    labels  img_size
  0% 0/142 [00:00<?, ?it/s]
  0% 0/142 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 659, in <module>
    main(opt)
  File "train.py", line 556, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 366, in train
    mloss = (mloss * i + loss_items) / (i + 1)  # update mean losses
RuntimeError: The size of tensor a (4) must match the size of tensor b (149) at non-singleton dimension 0
```

I still have no idea how to overcome it, do you have any?

**Comment by SSTato** [comment]
> 

Is your project based on the code I provided, or did you modify it yourself?

**Comment by Suppersine** [comment]
Some parts of my code are partially yours, as the rest belongs to yolov7-hbb by Wong-Kin-Yiu

**Comment by SSTato** [comment]
> Some parts of my code are partially yours, as the rest belongs to yolov7-hbb by Wong-Kin-Yiu

I took a cursory look at your code, I think it is because your test.py file is not modified correctly, I suggest you try with my val.py.
I'm sorry that I don't have a lot of energy to take a closer look at your code since it's the Chinese New Year holiday, so if you still need it, I can take a closer look for you when the holidays are over.
Happy Chinese New Year!

**Comment by Suppersine** [comment]
![image](https://user-images.githubusercontent.com/49264553/215389573-26d57a86-b489-46d6-949b-a7ff482167bf.png)
Another issue occurred again
It's in my newest repo here: https://github.com/Suppersine/YOLOv7_obb_KFIOU

**Comment by SSTato** [comment]
In fact, my code is really different from YOLOv7. If you want to modify it, my suggestion is to modify it on the basis of my code, rather than directly splice it with YOLOv7. By the way, my code can run normally. If you can't run correctly after modification, you can tell me what you modified.
